apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: container-env-secret
  namespace: backend
type: Opaque
data:
  JWT_KEY: cGV0bG92ZXI=
  CONNECTION_STRING: bW9uZ29kYitzcnY6Ly9mYW5nd2VpZG9uZzE5ODU6Wlh2Y0FFaWdXVlRCdXgwWUBwZXQuaWt5bW56eS5tb25nb2RiLm5ldC9wZXQtbG92ZXI=
  BUCKET: ZGV2LXBldGxvdmVy
  AWS_REGION: YXAtc291dGhlYXN0LTI=
  AWS_ACCESS_KEY_ID: QUtJQVFWVEVKMzRSS0dCUjNVVVE=
  AWS_SECRET_ACCESS_KEY: QXhJUyttakc4dndyakFxcmxJYVJ6ZDRuRWNGa3VScGdEbTlyM1g0cQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: techscrum
  namespace: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: techscrum
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: techscrum
      labels:
        app.kubernetes.io/name: techscrum
    spec:
      containers:
        - name: techscrum
          image: 046381260578.dkr.ecr.ap-southeast-2.amazonaws.com/pet-lover-uat:31
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: container-env-secret
                  key: JWT_KEY
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: container-env-secret
                  key: CONNECTION_STRING
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: container-env-secret
                  key: BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: container-env-secret
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: container-env-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: container-env-secret
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: techscrum
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: techscrum
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
---
apiVersion: v1
kind: Service
metadata:
  name: techscrum
  namespace: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/v1/health_check
  labels:
    app.kubernetes.io/name: techscrum
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30006
  selector:
    app.kubernetes.io/name: techscrum