projectName         = "techscrum"
s3_bucket_name      = "techscrum-p3"
lambda_zipfile_name = "backupTFstate.zip"
lambda_name         = "backupTFstate"
bucket_name         = "techscrum-tf-state-hub"
region              = "ap-southeast-2"
