apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: backend
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
      alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000