apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: backend
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      alb.ingress.kubernetes.io/healthcheck-path: /
  
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30001