S3_webhost_bucket = "techscrum-uat-frontend"
environment       = "uat"
projectName       = "techscrum"
root_domain       = "techscrumjr11.com"
region            = "ap-southeast-2"
hosted_zone_name  = "techscrumjr11.com"
