hosted_zone_name    = "techscrumjr11.com"
region              = "ap-southeast-2"
projectName         = "techscrum"
s3_bucket_name      = "techscrum-tf-lambda-uat"
lambda_zipfile_name = "failover.zip"
lambda_name         = "failover"
profile             = "Leo"
